INSERT INTO "countries" ("code", "name") VALUES ('CN', 'China');
INSERT INTO "countries" ("code", "name") VALUES ('IN', 'India');
INSERT INTO "countries" ("code", "name") VALUES ('US', 'United States');
INSERT INTO "countries" ("code", "name") VALUES ('ID', 'Indonesia');
INSERT INTO "countries" ("code", "name") VALUES ('BR', 'Brazil');
INSERT INTO "countries" ("code", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "countries" ("code", "name") VALUES ('BD', 'Bangladesh');
INSERT INTO "countries" ("code", "name") VALUES ('NG', 'Nigeria');
INSERT INTO "countries" ("code", "name") VALUES ('RU', 'Russia');
INSERT INTO "countries" ("code", "name") VALUES ('JP', 'Japan');
INSERT INTO "countries" ("code", "name") VALUES ('MX', 'Mexico');
INSERT INTO "countries" ("code", "name") VALUES ('PH', 'Philippines');
INSERT INTO "countries" ("code", "name") VALUES ('VN', 'Vietnam');
INSERT INTO "countries" ("code", "name") VALUES ('ET', 'Ethiopia');
INSERT INTO "countries" ("code", "name") VALUES ('DE', 'Germany');
INSERT INTO "countries" ("code", "name") VALUES ('EG', 'Egypt');
INSERT INTO "countries" ("code", "name") VALUES ('TR', 'Turkey');
INSERT INTO "countries" ("code", "name") VALUES ('IR', 'Iran');
INSERT INTO "countries" ("code", "name") VALUES ('CD', 'Democratic Republic of the Congo');
INSERT INTO "countries" ("code", "name") VALUES ('TH', 'Thailand');
INSERT INTO "countries" ("code", "name") VALUES ('FR', 'France');
INSERT INTO "countries" ("code", "name") VALUES ('GB', 'United Kingdom');
INSERT INTO "countries" ("code", "name") VALUES ('IT', 'Italy');
INSERT INTO "countries" ("code", "name") VALUES ('MM', 'Myanmar');
INSERT INTO "countries" ("code", "name") VALUES ('ZA', 'South Africa');
INSERT INTO "countries" ("code", "name") VALUES ('KR', 'South Korea');
INSERT INTO "countries" ("code", "name") VALUES ('CO', 'Colombia');
INSERT INTO "countries" ("code", "name") VALUES ('ES', 'Spain');
INSERT INTO "countries" ("code", "name") VALUES ('UA', 'Ukraine');
INSERT INTO "countries" ("code", "name") VALUES ('TZ', 'Tanzania');
INSERT INTO "countries" ("code", "name") VALUES ('AR', 'Argentina');
INSERT INTO "countries" ("code", "name") VALUES ('KE', 'Kenya');
INSERT INTO "countries" ("code", "name") VALUES ('PL', 'Poland');
INSERT INTO "countries" ("code", "name") VALUES ('SD', 'Sudan');
INSERT INTO "countries" ("code", "name") VALUES ('DZ', 'Algeria');
INSERT INTO "countries" ("code", "name") VALUES ('MA', 'Morocco');
INSERT INTO "countries" ("code", "name") VALUES ('CA', 'Canada');
INSERT INTO "countries" ("code", "name") VALUES ('UG', 'Uganda');
INSERT INTO "countries" ("code", "name") VALUES ('PE', 'Peru');
INSERT INTO "countries" ("code", "name") VALUES ('IQ', 'Iraq');
INSERT INTO "countries" ("code", "name") VALUES ('AF', 'Afghanistan');
INSERT INTO "countries" ("code", "name") VALUES ('NP', 'Nepal');
INSERT INTO "countries" ("code", "name") VALUES ('MY', 'Malaysia');
INSERT INTO "countries" ("code", "name") VALUES ('UZ', 'Uzbekistan');
INSERT INTO "countries" ("code", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "countries" ("code", "name") VALUES ('SA', 'Saudi Arabia');

INSERT INTO users (id, username, email, gender, birthday, country_code) VALUES (1, 'vasya.pupkin', 'vasya.pupkin@example.ru', 'male', '1993-09-15', 'RU');
INSERT INTO users (id, username, email, gender, birthday, country_code) VALUES (2, 'ivan.petrov', 'ivan.petrov@example.ru', 'male', '1978-04-05', 'RU');
INSERT INTO users (id, username, email, gender, birthday, country_code) VALUES (3, 'ann.gorshkova', 'ann.gorshkova@example.ru', 'female', '1988-01-13', 'RU');
INSERT INTO users (id, username, email, gender, birthday, country_code) VALUES (4, 'olga.petrova', 'olga.petrova@example.ru', 'female', '1988-04-13', 'RU');
INSERT INTO users (id, username, email, gender, birthday, country_code) VALUES (5, 'dmitry.barin', 'dmitry.barin@example.ru', 'male', '1988-02-13', 'RU');

ALTER SEQUENCE users_id_seq restart with 6;
